//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddsWaffle.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_EddsWaffleEntities : DbContext
    {
        public DB_EddsWaffleEntities()
            : base("name=DB_EddsWaffleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Membership> Membership { get; set; }
        public virtual DbSet<MemberTransaction> MemberTransaction { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<TesTes_Table> TesTes_Table { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Prediction> Prediction { get; set; }
        public virtual DbSet<TransactionDetails> TransactionDetails { get; set; }
        public virtual DbSet<DetailTransaction> DetailTransaction { get; set; }
        public virtual DbSet<LowIncome> LowIncome { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Recommendation> Recommendation { get; set; }
        public virtual DbSet<ItemSold> ItemSold { get; set; }
        public virtual DbSet<TopIncome> TopIncome { get; set; }
        public virtual DbSet<TransactionHeader> TransactionHeader { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<MAPE> MAPE { get; set; }
        public virtual DbSet<PotentialProduct> PotentialProduct { get; set; }
        public virtual DbSet<PredictParameter> PredictParameter { get; set; }
        public virtual DbSet<TrendsParameter> TrendsParameter { get; set; }
    }
}
