//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddsWaffle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LowIncome
    {
        public decimal id_lowincome { get; set; }
        public Nullable<decimal> ranking_lowincome { get; set; }
        public Nullable<decimal> total_lowincome { get; set; }
        public string date_lowincome { get; set; }
    }
}
