//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddsWaffle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public string code_member { get; set; }
        public string name_member { get; set; }
        public System.DateTime borndate_member { get; set; }
        public string gender_member { get; set; }
        public decimal phone_member { get; set; }
        public string address_member { get; set; }
    }
}
