//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddsWaffle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public decimal number_transaction { get; set; }
        public Nullable<decimal> code_transaction { get; set; }
        public string code_product { get; set; }
        public string name_product { get; set; }
        public Nullable<decimal> quantity_product { get; set; }
        public Nullable<decimal> price_product { get; set; }
    }
}
