//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddsWaffle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PotentialProduct
    {
        public decimal id_potential { get; set; }
        public string product_potential { get; set; }
        public Nullable<decimal> product_number { get; set; }
    }
}
