//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddsWaffle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public decimal id_recommendation { get; set; }
        public string item_combination { get; set; }
        public Nullable<decimal> total_value { get; set; }
    }
}
