//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddsWaffle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHeader
    {
        public decimal code_transaction { get; set; }
        public System.DateTime date_time { get; set; }
        public Nullable<decimal> discount_transaction { get; set; }
        public string payment_method { get; set; }
        public decimal payment_total { get; set; }
    }
}
